fix: page scroll
institutoreditus/reditus pull request #103
Opened 2022-09-22 22:28 UTC by estevamfurtado

Impactos
- É possível rolar a página de entrada quando o conteúdo da direita/esquerda ultrapassa a tela no browser do PC.
- Conteúdo da direita está centralizado.
- Quando há redução vertical da tela e a caixa da esquerda some, a caixa da direita se extende.

Notas
- A maior parte das mudanças foram de .css, mas o PR troca o uso do @rmwc/grid por uma estrutura de flexbox simples, mais fácil de lapidar.

O gif abaixo mostra a diferença entre o antes e dps das mudanças do PR.

![Recording 2022-09-22 at 19 27 05](https://user-images.githubusercontent.com/15219345/191862241-da31c77f-3df4-4cdb-87fe-dc93cabc9689.gif)

2022-10-17 22:45 UTC, rafaelcf0 requested changes
De uma olhada nos warnings do linter

2022-10-17 22:45 UTC, rafaelcf0 commented on pages/index.module.css
> +  color: white;
Ordem abc, se possivel

2022-10-17 22:45 UTC, rafaelcf0 commented on pages/index.module.css
> +  height: 100vh;
abc

2022-10-27 12:22 UTC, estevamfurtado commented
As mudanças propostas aqui já foram incorporadas em outro PR.

2022-10-27 12:22 UTC, closed without merging